"""Learning event model for car device telemetry."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Index, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class LearningEvent(Base):
    """An idempotent learning event reported by a car device.

    event_id is generated by the car (UUID v4) and used for
    idempotency: duplicate (device_id, event_id) pairs are silently
    accepted but not duplicated.
    """

    __tablename__ = "learning_event"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    device_id: Mapped[str] = mapped_column(
        Text,
        ForeignKey("device_binding.device_id"),
        nullable=False,
    )
    child_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("child.id"),
        nullable=False,
    )
    event_id: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="Client-generated idempotency key (UUID v4)"
    )
    event_type: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="e.g. learning.session.start, learning.answer.submit"
    )
    module: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        comment="One of: science, math, english, poems, music, quiz"
    )
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        comment="Event occurrence time from the device"
    )
    payload: Mapped[dict] = mapped_column(
        JSONB, nullable=False, default=dict,
        comment="Arbitrary event data"
    )
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Server receive time"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    __table_args__ = (
        UniqueConstraint("device_id", "event_id", name="uq_learning_event_device_event"),
        Index("idx_learning_event_device", "device_id"),
        Index("idx_learning_event_child", "child_id"),
        Index("idx_learning_event_type", "event_type"),
        Index("idx_learning_event_timestamp", "timestamp"),
    )
