"""Notification settings and notification models."""

import uuid
from datetime import datetime, time

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Text,
    Time,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class NotificationSettings(Base):
    """Per-child notification preferences set by parent.

    One row per child. settings is a JSONB dict of boolean toggles.
    dnd (do-not-disturb) silences all notifications during the window.
    """

    __tablename__ = "notification_settings"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    child_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("child.id"), nullable=False
    )
    settings: Mapped[dict] = mapped_column(
        JSONB, nullable=False, default=dict,
        comment="e.g. {task_completed: true, behavior_alert: true, ...}"
    )
    dnd_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    dnd_start_time: Mapped[time | None] = mapped_column(Time, nullable=True)
    dnd_end_time: Mapped[time | None] = mapped_column(Time, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    __table_args__ = (
        UniqueConstraint("child_id", name="uq_notif_settings_child"),
        Index("idx_notif_settings_child", "child_id"),
    )


class Notification(Base):
    """A single notification delivered to a parent.

    Notifications are generated by the backend in response to car events
    (task completed, behavior alert, device offline, etc.).
    """

    __tablename__ = "notification"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    parent_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("parent_account.id"), nullable=False
    )
    child_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("child.id"), nullable=False
    )
    notif_type: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="task_completed|behavior_alert|device_offline|daily_summary|weekly_report|..."
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    is_read: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    read_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index("idx_notif_parent", "parent_id"),
        Index("idx_notif_parent_read", "parent_id", "is_read"),
        Index("idx_notif_created", "created_at"),
    )
